verversion: "3.8"

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
      - MYSQL_USER=angel
      - MYSQL_PASSWORD=110202
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/init.sql
  
  angel:
    build:
    depends_on:
      - mysqldb
    ports:
      - "3000:3000"